image: chef/chefworkstation:latest
variables:
  CHEF_LICENSE: accept-no-persist
stages:
  - acceptance
  - test

.acc: &acc
  stage: acceptance
  tags:
    - docker
unit:
  <<: *acc
  script:
    - delivery local unit
lint:
  <<: *acc
  script:
    - delivery local lint
syntax:
  <<: *acc
  script:
    - delivery local syntax

test kitchen:
  stage: test
  script:
    - kitchen converge
