image: chef/chefworkstation:latest
variables:
  CHEF_LICENSE: accept-no-persist
  DEBUG_KITCHEN_CLEANUP_ON_FAILURE: /bin/true
stages:
  - acceptance
  - test
  - build
  - publish

### Acceptance Phase
.acc: &acc
  stage: acceptance
  tags:
    - docker

.habitat-setup: &habitat-setup
  before_script:
    - mkdir -p /hab/cache/keys

Unit:
  <<: *acc
  script:
    - delivery local unit
Lint:
  <<: *acc
  script:
    - delivery local lint
Syntax:
  <<: *acc
  script:
    - delivery local syntax

### Test Phase
Test Kitchen:
  stage: test
  tags:
    - docker01-wks
  script:
    # - delivery local acceptance
    - echo 'ok we need to come back to this'
  after_script:
    # - ${DEBUG_KITCHEN_CLEANUP_ON_FAILURE} && delivery local cleanup
    - echo 'after script'

### Build Phase
Build Habitat Artifact:
  stage: build
  tags:
    - docker
  <<: *habitat-setup
  script:
    - hab pkg build .
  artifacts:
    paths:
      - results/*

### Publish Phase
Publish to bldr.habitat.sh:
  stage: publish
  tags:
    - docker01
  script:
    - source results/last_build.env
    - hab pkg upload "results/${pkg_artifact}"

Publish to Supermarket:
  stage: publish
  tags:
    - docker01
  script:
    - knife supermarket share
